### ISSUE TITLE
functions needed from frontend

### ISSUE THREAD

**Issue by lyh552506** [lyh552506/SB-compiler#1]
1.deal with the User* ->GetParents
2.delete a block
3.inserting a instruction anywhere in the block

**Comment by RicoAfoat** [comment]
Do you mean:

1. To know where the value is defined? (params, global and defined in basicblocks)
2. Delete a `BasicBlock` and modify relevant branch inst?(Condition branch -> UnCondition branch) 
3. Duplicated with #9
