### ISSUE TITLE
Need Macro Function: LIST_INSERT_BEFORE & LIST_INSERT_AFTER

### ISSUE THREAD

**Issue by NanQin555** [lyh552506/SB-compiler#9]
LIST_INSERT_BEFORE(newly_inst, bb,it) 
LIST_INSERT_AFTER(newly_inst, bb,it)

**Comment by RicoAfoat** [comment]
@lyh552506  Try it again

**Comment by lyh552506** [comment]
> @lyh552506 Try it again

Done successfully!
